/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseNode: typeof import('./src/components/nodes/BaseNode.vue')['default']
    BranchEdge: typeof import('./src/components/workflow/BranchEdge.vue')['default']
    ChatMessagesPanel: typeof import('./src/components/chat/ChatMessagesPanel.vue')['default']
    ChatSessionsPanel: typeof import('./src/components/chat/ChatSessionsPanel.vue')['default']
    ChatSourceDrawer: typeof import('./src/components/chat/ChatSourceDrawer.vue')['default']
    CodeNode: typeof import('./src/components/nodes/CodeNode.vue')['default']
    ComponentLibrary: typeof import('./src/components/workflow/studio/ComponentLibrary.vue')['default']
    ConditionNode: typeof import('./src/components/nodes/ConditionNode.vue')['default']
    DebugPanel: typeof import('./src/components/workflow/DebugPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EndNode: typeof import('./src/components/nodes/EndNode.vue')['default']
    ExecutionDetailDialog: typeof import('./src/components/workflow/ExecutionDetailDialog.vue')['default']
    HttpNode: typeof import('./src/components/nodes/HttpNode.vue')['default']
    KnowledgeDocDrawer: typeof import('./src/components/knowledge/KnowledgeDocDrawer.vue')['default']
    KnowledgeDocumentsPanel: typeof import('./src/components/knowledge/KnowledgeDocumentsPanel.vue')['default']
    KnowledgeEvalPanel: typeof import('./src/components/knowledge/KnowledgeEvalPanel.vue')['default']
    KnowledgeEvalResults: typeof import('./src/components/knowledge/KnowledgeEvalResults.vue')['default']
    KnowledgeNode: typeof import('./src/components/nodes/KnowledgeNode.vue')['default']
    KnowledgeResults: typeof import('./src/components/knowledge/KnowledgeResults.vue')['default']
    KnowledgeSearchPanel: typeof import('./src/components/knowledge/KnowledgeSearchPanel.vue')['default']
    LLMNode: typeof import('./src/components/nodes/LLMNode.vue')['default']
    MetricsLineChart: typeof import('./src/components/monitoring/MetricsLineChart.vue')['default']
    MonitoringDailyTable: typeof import('./src/components/monitoring/MonitoringDailyTable.vue')['default']
    MonitoringToolbar: typeof import('./src/components/monitoring/MonitoringToolbar.vue')['default']
    MonitoringTrends: typeof import('./src/components/monitoring/MonitoringTrends.vue')['default']
    NodeConfigDrawer: typeof import('./src/components/workflow/NodeConfigDrawer.vue')['default']
    NodePolicyFields: typeof import('./src/components/workflow/NodePolicyFields.vue')['default']
    NodeToolbar: typeof import('./src/components/workflow/NodeToolbar.vue')['default']
    PropertiesPanel: typeof import('./src/components/workflow/studio/PropertiesPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudioHeader: typeof import('./src/components/workflow/studio/StudioHeader.vue')['default']
    TriggerNode: typeof import('./src/components/nodes/TriggerNode.vue')['default']
    WorkflowCanvasPanel: typeof import('./src/components/workflow/panels/WorkflowCanvasPanel.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
